
#
# This is 1 of ZAWA's 10 habitat ranges. Each sub-range has its own list of biomes, and all of the sub-range's entities will spawn in those biomes.
# Disable entities (or a species variant) by setting "enabled" under their category to false.
# Use ONLY whole numbers greater than 0 for chance, min, and max!
# "chance" is how common they spawn, a higher number is more common than a lower number. "min" and "max" adjusts their spawning group size.
# !! If modded biomes are not generated, delete the entire "biomes" line for each sub-category and restart minecraft. !!
#
#
[cold_grassland]
	biomes = ["minecraft:plains", "minecraft:snowy_tundra", "minecraft:sunflower_plains"]

[dry_grassland]
	biomes = ["minecraft:plains", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:sunflower_plains", "minecraft:badlands", "minecraft:badlands_plateau"]

	[dry_grassland.gerenuk]
		chance = 2
		min = 2
		max = 3
		enabled = true

	[dry_grassland.arizona_bark_scorpion]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_grassland.swamp_monkey]
		chance = 2
		min = 2
		max = 3
		enabled = true

	[dry_grassland.peccary]
		chance = 2
		min = 2
		max = 3
		enabled = true

	[dry_grassland.northern_scorpion]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_grassland.potto]
		chance = 2
		min = 2
		max = 3
		enabled = true

	[dry_grassland.african_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_grassland.giant_anteater]
		chance = 8
		min = 1
		max = 1
		enabled = true

	[dry_grassland.black_footed_ferret]
		chance = 5
		min = 1
		max = 2
		enabled = true

	[dry_grassland.butterfly]
		chance = 10
		min = 1
		max = 4
		enabled = true

	[dry_grassland.brazilian_black_tarantula]
		chance = 4
		min = 1
		max = 1
		enabled = true

	[dry_grassland.devils_flower_praying_mantis]
		chance = 4
		min = 1
		max = 1
		enabled = true

